[package]
license.workspace = true
name = "moli-file-api"
version = "0.1.0"
edition = "2024"

[dependencies]
base64 = "0.22"
encoding_rs = "0.8"
getrandom = "0.3"
moli-web-mime = { path = "../moli-web-mime" }
parking_lot = "0.12"
uuid = { version = "1.23.1", default-features = false }

[lints]
workspace = true
