[package]
license.workspace = true
name = "moli-v8-platform"
version = "0.1.0"
edition = "2024"

[dependencies]
crossbeam-utils = "0.8.21"
parking_lot = "0.12"
tokio = { version = "1.51.0", features = ["rt", "sync", "time"] }
tracing = "0.1.41"
v8 = "146.8.0"

[dev-dependencies]
moli-v8-init = { path = "../moli-v8-init" }
serde_json = "1.0.145"

[lints]
workspace = true
