#[derive(Clone, Copy, PartialEq, Eq)]
pub(in crate::context_bootstrap) enum EventSubclassKind {
    UiEvent = 1,
    FocusEvent = 2,
    TextEvent = 3,
    CompositionEvent = 4,
    CustomEvent = 5,
    MouseEvent = 6,
    KeyboardEvent = 7,
    WheelEvent = 8,
    PointerEvent = 9,
    TouchEvent = 10,
    MessageEvent = 11,
    ErrorEvent = 12,
    PromiseRejectionEvent = 13,
    NavigationCurrentEntryChangeEvent = 14,
    CloseEvent = 15,
    DragEvent = 16,
    SubmitEvent = 17,
    FormDataEvent = 18,
    InputEvent = 19,
    PopStateEvent = 20,
    PageTransitionEvent = 21,
    CommandEvent = 22,
    ToggleEvent = 23,
    TrackEvent = 24,
    InterestEvent = 25,
    NavigateEvent = 26,
    StorageEvent = 27,
    SecurityPolicyViolationEvent = 28,
    ClipboardEvent = 29,
    CapturedMouseEvent = 30,
    FontFaceSetLoadEvent = 31,
}

impl EventSubclassKind {
    pub(super) fn from_i32(value: i32) -> Option<Self> {
        match value {
            1 => Some(Self::UiEvent),
            2 => Some(Self::FocusEvent),
            3 => Some(Self::TextEvent),
            4 => Some(Self::CompositionEvent),
            5 => Some(Self::CustomEvent),
            6 => Some(Self::MouseEvent),
            7 => Some(Self::KeyboardEvent),
            8 => Some(Self::WheelEvent),
            9 => Some(Self::PointerEvent),
            10 => Some(Self::TouchEvent),
            11 => Some(Self::MessageEvent),
            12 => Some(Self::ErrorEvent),
            13 => Some(Self::PromiseRejectionEvent),
            14 => Some(Self::NavigationCurrentEntryChangeEvent),
            15 => Some(Self::CloseEvent),
            16 => Some(Self::DragEvent),
            17 => Some(Self::SubmitEvent),
            18 => Some(Self::FormDataEvent),
            19 => Some(Self::InputEvent),
            20 => Some(Self::PopStateEvent),
            21 => Some(Self::PageTransitionEvent),
            22 => Some(Self::CommandEvent),
            23 => Some(Self::ToggleEvent),
            24 => Some(Self::TrackEvent),
            25 => Some(Self::InterestEvent),
            26 => Some(Self::NavigateEvent),
            27 => Some(Self::StorageEvent),
            28 => Some(Self::SecurityPolicyViolationEvent),
            29 => Some(Self::ClipboardEvent),
            30 => Some(Self::CapturedMouseEvent),
            31 => Some(Self::FontFaceSetLoadEvent),
            _ => None,
        }
    }

    pub(super) fn constructor_name(self) -> &'static str {
        match self {
            Self::UiEvent => "UIEvent",
            Self::FocusEvent => "FocusEvent",
            Self::TextEvent => "TextEvent",
            Self::CompositionEvent => "CompositionEvent",
            Self::CustomEvent => "CustomEvent",
            Self::MouseEvent => "MouseEvent",
            Self::KeyboardEvent => "KeyboardEvent",
            Self::WheelEvent => "WheelEvent",
            Self::PointerEvent => "PointerEvent",
            Self::TouchEvent => "TouchEvent",
            Self::MessageEvent => "MessageEvent",
            Self::ErrorEvent => "ErrorEvent",
            Self::PromiseRejectionEvent => "PromiseRejectionEvent",
            Self::NavigationCurrentEntryChangeEvent => "NavigationCurrentEntryChangeEvent",
            Self::CloseEvent => "CloseEvent",
            Self::DragEvent => "DragEvent",
            Self::SubmitEvent => "SubmitEvent",
            Self::FormDataEvent => "FormDataEvent",
            Self::InputEvent => "InputEvent",
            Self::PopStateEvent => "PopStateEvent",
            Self::PageTransitionEvent => "PageTransitionEvent",
            Self::CommandEvent => "CommandEvent",
            Self::ToggleEvent => "ToggleEvent",
            Self::TrackEvent => "TrackEvent",
            Self::InterestEvent => "InterestEvent",
            Self::NavigateEvent => "NavigateEvent",
            Self::StorageEvent => "StorageEvent",
            Self::SecurityPolicyViolationEvent => "SecurityPolicyViolationEvent",
            Self::ClipboardEvent => "ClipboardEvent",
            Self::CapturedMouseEvent => "CapturedMouseEvent",
            Self::FontFaceSetLoadEvent => "FontFaceSetLoadEvent",
        }
    }
}
