use super::*;

#[tokio::test]
async fn websocket_handshake_inherits_origin_user_agent_and_extra_headers() {
    run_page_vm_async_test(async move {
        let (url, headers_rx, server) = spawn_header_capture_websocket_server().await;
        let url_literal = serde_json::to_string(&url).expect("serialize websocket url");
        let mut config = FetchConfig::default();
        config.set_user_agent("Moli-WebSocket-Test/1.0");
        let mut page_vm = test_page_vm_with_config(
            config,
            vec![
                ("X-Moli-Trace".to_owned(), "socket".to_owned()),
                // Protocol control headers are generated by tungstenite and must not be
                // overridden by page-level extra headers.
                ("Sec-WebSocket-Version".to_owned(), "999".to_owned()),
            ],
        );
        let local_executor = page_vm.local_executor.clone();

        let headers = local_executor
            .run(async move {
                page_vm
                    .vm_mut()
                    .eval(&format!("new WebSocket({url_literal})"))?;
                tokio::time::timeout(Duration::from_secs(3), headers_rx)
                    .await
                    .map_err(|_| anyhow::anyhow!("websocket handshake headers did not arrive"))?
                    .map_err(|_| anyhow::anyhow!("websocket header sender dropped"))
            })
            .await
            .expect("websocket header test should run on owner lane");
        server.await.expect("websocket header server should finish");

        assert_eq!(
            header_value(&headers, "origin").as_deref(),
            Some("https://example.com")
        );
        assert_eq!(
            header_value(&headers, "user-agent").as_deref(),
            Some("Moli-WebSocket-Test/1.0")
        );
        assert_eq!(
            header_value(&headers, "x-moli-trace").as_deref(),
            Some("socket")
        );
        assert_eq!(
            header_value(&headers, "sec-websocket-version").as_deref(),
            Some("13")
        );
    })
    .await;
}

#[tokio::test]
async fn websocket_handshake_omits_referer_header_like_fetch() {
    run_page_vm_async_test(async move {
        let (url, headers_rx, server) = spawn_header_capture_websocket_server().await;
        let url_literal = serde_json::to_string(&url).expect("serialize websocket url");
        let mut page_vm = test_page_vm_with_document_url(
            Url::parse("https://example.com/referrer-source").expect("page url"),
        );
        let local_executor = page_vm.local_executor.clone();

        let headers = local_executor
            .run(async move {
                page_vm
                    .vm_mut()
                    .eval(&format!("new WebSocket({url_literal})"))?;
                tokio::time::timeout(Duration::from_secs(3), headers_rx)
                    .await
                    .map_err(|_| anyhow::anyhow!("websocket referrer headers did not arrive"))?
                    .map_err(|_| anyhow::anyhow!("websocket referrer header sender dropped"))
            })
            .await
            .expect("websocket referrer test should run on owner lane");
        server
            .await
            .expect("websocket referrer header server should finish");

        assert_eq!(header_value(&headers, "referer"), None);
    })
    .await;
}

#[tokio::test]
async fn websocket_handshake_inherits_browser_cookie_store() {
    run_page_vm_async_test(async move {
        let (url, headers_rx, server) = spawn_header_capture_websocket_server().await;
        let url_literal = serde_json::to_string(&url).expect("serialize websocket url");
        let cookie_store = moli_cookie_jar::new_shared_browser_cookie_store();
        let ws_url = Url::parse(&url).expect("websocket url");
        let cookie_url = moli_websocket::websocket_cookie_url(&ws_url);
        {
            let mut store = cookie_store.lock();
            let reports = store.store_response_headers_with_reports(
                &cookie_url,
                &[(
                    "set-cookie".to_owned(),
                    "sid=server; Path=/; HttpOnly".to_owned(),
                )],
            );
            assert!(reports.iter().any(|report| report.is_accepted()));
        }
        let loader = crate::network::ResourceRequestClient::new_with_cookie_store(
            &FetchConfig::default(),
            cookie_store,
        )
        .expect("loader with cookie store");
        let mut page_vm = test_page_vm_with_loader(&loader, Vec::new());
        let local_executor = page_vm.local_executor.clone();

        let headers = local_executor
            .run(async move {
                page_vm
                    .vm_mut()
                    .eval(&format!("new WebSocket({url_literal})"))?;
                tokio::time::timeout(Duration::from_secs(3), headers_rx)
                    .await
                    .map_err(|_| anyhow::anyhow!("websocket handshake headers did not arrive"))?
                    .map_err(|_| anyhow::anyhow!("websocket header sender dropped"))
            })
            .await
            .expect("websocket cookie test should run on owner lane");
        server.await.expect("websocket header server should finish");

        assert_eq!(
            header_value(&headers, "cookie").as_deref(),
            Some("sid=server")
        );
    })
    .await;
}

#[tokio::test]
async fn websocket_handshake_respects_disabled_tls_verify_for_self_signed_wss() {
    run_page_vm_async_test(async move {
        let (url, headers_rx, server) = spawn_tls_header_capture_websocket_server().await;
        let url_literal = serde_json::to_string(&url).expect("serialize websocket url");
        let mut config = FetchConfig::default();
        config.set_tls_verify_host(false);
        let mut page_vm = test_page_vm_with_config(config, Vec::new());
        let local_executor = page_vm.local_executor.clone();

        let headers = local_executor
            .run(async move {
                page_vm
                    .vm_mut()
                    .eval(&format!("new WebSocket({url_literal})"))?;
                tokio::time::timeout(Duration::from_secs(3), headers_rx)
                    .await
                    .map_err(|_| anyhow::anyhow!("websocket TLS handshake headers did not arrive"))?
                    .map_err(|_| anyhow::anyhow!("websocket TLS header sender dropped"))
            })
            .await
            .expect("websocket TLS verify test should run on owner lane");
        server
            .await
            .expect("websocket TLS header server should finish");

        assert_eq!(
            header_value(&headers, "origin").as_deref(),
            Some("https://example.com")
        );
    })
    .await;
}

#[tokio::test]
async fn websocket_handshake_uses_explicit_http_proxy_connect() {
    run_page_vm_async_test(async move {
        let (url, headers_rx, server) = spawn_header_capture_websocket_server().await;
        let (proxy_url, proxy_request_rx, proxy) = spawn_http_connect_proxy().await;
        let url_literal = serde_json::to_string(&url).expect("serialize websocket url");
        let mut config = FetchConfig::default();
        config.set_proxy_options(Some(proxy_url), Some("proxy-token".to_owned()));
        config.set_http_no_proxy(Some(String::new()));
        let mut page_vm = test_page_vm_with_config(config, Vec::new());
        let local_executor = page_vm.local_executor.clone();

        let (proxy_request, headers) = local_executor
            .run(async move {
                page_vm
                    .vm_mut()
                    .eval(&format!("new WebSocket({url_literal})"))?;
                let proxy_request = tokio::time::timeout(Duration::from_secs(3), proxy_request_rx)
                    .await
                    .map_err(|_| anyhow::anyhow!("websocket proxy CONNECT did not arrive"))?
                    .map_err(|_| anyhow::anyhow!("websocket proxy sender dropped"))?;
                let headers = tokio::time::timeout(Duration::from_secs(3), headers_rx)
                    .await
                    .map_err(|_| anyhow::anyhow!("websocket handshake headers did not arrive"))?
                    .map_err(|_| anyhow::anyhow!("websocket header sender dropped"))?;
                Ok::<_, anyhow::Error>((proxy_request, headers))
            })
            .await
            .expect("websocket proxy test should run on owner lane");
        server.await.expect("websocket header server should finish");
        proxy.await.expect("websocket proxy should finish");

        let target = Url::parse(&url).expect("websocket target url");
        let expected_connect = format!(
            "CONNECT {}:{} HTTP/1.1",
            target.host_str().expect("target host"),
            target.port_or_known_default().expect("target port")
        );
        assert!(
            proxy_request.starts_with(&expected_connect),
            "unexpected CONNECT request: {proxy_request:?}"
        );
        assert!(
            proxy_request.contains("\r\nProxy-Authorization: Bearer proxy-token\r\n"),
            "proxy bearer token should be sent only on CONNECT: {proxy_request:?}"
        );
        assert_eq!(
            header_value(&headers, "origin").as_deref(),
            Some("https://example.com")
        );
        assert_eq!(header_value(&headers, "proxy-authorization"), None);
    })
    .await;
}

#[tokio::test]
async fn websocket_handshake_failure_records_network_trace_entry() {
    run_page_vm_async_test(async move {
        let (url, server) = spawn_dropping_websocket_server().await;
        let url_literal = serde_json::to_string(&url).expect("serialize websocket url");
        let mut page_vm = test_page_vm();
        let local_executor = page_vm.local_executor.clone();

        let network_output = local_executor
            .run(async move {
                page_vm.vm_mut().eval(&format!(
                    r#"
                    (() => {{
                        const socket = new WebSocket({url_literal});
                        globalThis.__wsFailed = false;
                        globalThis.__wsClosed = false;
                        socket.addEventListener('error', () => {{
                            globalThis.__wsFailed = true;
                        }});
                        socket.addEventListener('close', () => {{
                            globalThis.__wsClosed = true;
                        }});
                    }})()
                    "#
                ))?;

                for _ in 0..20 {
                    while page_vm
                        .run_exact_page_websocket_selected_task_for_test()
                        .await?
                        .is_some()
                    {}
                    if page_vm.vm_mut().eval(
                        "String(globalThis.__wsFailed === true && globalThis.__wsClosed === true)",
                    )? == "true"
                    {
                        break;
                    }
                    let arrived = tokio::time::timeout(
                        Duration::from_secs(1),
                        page_vm.wait_for_page_work_arrival_without_timeout(false),
                    )
                    .await
                    .unwrap_or(false);
                    assert!(arrived, "websocket failure event should arrive");
                }
                while page_vm
                    .run_exact_page_websocket_selected_task_for_test()
                    .await?
                    .is_some()
                {}
                assert_eq!(
                    page_vm.vm_mut().eval(
                        "String(globalThis.__wsFailed === true && globalThis.__wsClosed === true)"
                    )?,
                    "true"
                );
                Ok::<_, anyhow::Error>(page_vm.vm_mut().take_network_output())
            })
            .await
            .expect("websocket failure trace test should run on owner lane");
        server.await.expect("websocket drop server should finish");
        let (records, _frame_events, lifecycle_events) = split_network_output_items(network_output);

        assert_eq!(records.len(), 1);
        let record = &records[0];
        assert_eq!(record.resource_type(), SubresourceResourceType::WebSocket);
        assert_eq!(record.method(), "GET");
        assert_eq!(record.url().as_str(), url);
        match record.outcome() {
            SubresourceNetworkOutcome::Failure { error_text } => {
                assert!(error_text.contains("WebSocket connection failed"));
            }
            outcome => panic!("expected websocket failure record, got {outcome:?}"),
        }
        assert_eq!(lifecycle_events.len(), 2);
        assert_eq!(
            lifecycle_events[0].kind(),
            crate::types::WebSocketLifecycleKind::Error
        );
        assert!(
            lifecycle_events[0]
                .error_text()
                .is_some_and(|text| text.contains("WebSocket connection failed"))
        );
        assert_eq!(
            lifecycle_events[1].kind(),
            crate::types::WebSocketLifecycleKind::Close
        );
        assert_eq!(lifecycle_events[1].close_code(), Some(1006));
        assert_eq!(lifecycle_events[1].was_clean(), Some(false));
    })
    .await;
}
