[package]
license.workspace = true
name = "moli-protocol-cdp"
version = "0.1.0"
edition = "2024"

[dependencies]
moli-page-types = { path = "../moli-page-types" }
moli-time = { path = "../moli-time" }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"

[lints]
workspace = true
