[package]
license.workspace = true
name = "moli-dom"
version = "0.1.0"
edition = "2024"

[dependencies]
html5ever = "0.39.0"
indexmap = "2.6"
moli-css-parse = { path = "../moli-css-parse" }
moli-html-input-temporal = { path = "../moli-html-input-temporal" }
percent-encoding = "2.3"
selectors = "0.40"
serde_json = "1.0.145"
thin-vec = "0.2.14"
url = "2.5.7"

[lints]
workspace = true
