[package]
name = "moli-image"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"

[dependencies]
image = { version = "0.25.10", default-features = false, features = ["gif", "webp"] }
jpeg-decoder = "0.3"
jpeg-encoder = "0.6"
png = "0.18"
thiserror = "2.0.17"
usvg = { version = "=0.48.1", default-features = true }
xmlparser = "0.13.6"

[lints]
workspace = true
