[package]
license.workspace = true
name = "moli-cookie-jar"
version = "0.1.0"
edition = "2024"

[features]
default = []
test-support = []

[dependencies]
cookie_store = { package = "moli-cookie-store", path = "../moli-cookie-store", default-features = false, features = ["public_suffix"] }
moli-site = { path = "../moli-site" }
moli-storage-key = { path = "../moli-storage-key" }
parking_lot = "0.12"
time = "0.3"
tracing = "0.1.41"
url = "2.5.7"

[lints]
workspace = true
