[package]
license.workspace = true
name = "moli-import-map"
version = "0.1.0"
edition = "2024"

[dependencies]
import_map = { version = "0.25.0", default-features = false }
moli-page-types = { path = "../moli-page-types" }
moli-script = { path = "../moli-script" }
serde_json = "1.0.145"
url = "2.5.7"

[lints]
workspace = true
