#[derive(Clone, Copy, PartialEq, Eq)]
pub(in crate::context_bootstrap) enum ConstructorKind {
    Illegal,
    Unsupported,
    Event,
    UiEvent,
    FocusEvent,
    CompositionEvent,
    CustomEvent,
    MouseEvent,
    CapturedMouseEvent,
    DragEvent,
    ClipboardEvent,
    KeyboardEvent,
    InputEvent,
    WheelEvent,
    PointerEvent,
    TouchEvent,
    MessageEvent,
    StorageEvent,
    ErrorEvent,
    PromiseRejectionEvent,
    SecurityPolicyViolationEvent,
    NavigationCurrentEntryChangeEvent,
    NavigateEvent,
    CloseEvent,
    SubmitEvent,
    FormDataEvent,
    CommandEvent,
    ToggleEvent,
    InterestEvent,
    PopStateEvent,
    PageTransitionEvent,
    DomException,
    DomError,
    QuotaExceededError,
    CustomElementRegistry,
    Document,
    DocumentFragment,
    XmlHttpRequest,
    Headers,
    Request,
    Response,
    ProgressEvent,
    DomParser,
    TextEncoder,
    TextDecoder,
    ReadableStream,
    ReadableStreamDefaultReader,
    ReadableStreamByobReader,
    ReadableStreamDefaultController,
    WritableStream,
    WritableStreamDefaultWriter,
    WritableStreamDefaultController,
    TransformStream,
    TransformStreamDefaultController,
    TextEncoderStream,
    TextDecoderStream,
    ByteLengthQueuingStrategy,
    CountQueuingStrategy,
    Blob,
    DataTransfer,
    ImageData,
    OffscreenCanvas,
    CanvasRenderingContext2D,
    OffscreenCanvasRenderingContext2D,
    WebGLRenderingContext,
    WebGlDebugRendererInfo,
    WebGlLoseContext,
    File,
    FileList,
    FileReader,
    FileReaderSync,
    XmlSerializer,
    AbortController,
    BroadcastChannel,
    EventSource,
    IdleDetector,
    Notification,
    MessageChannel,
    MessagePort,
    Worker,
    SharedWorker,
    WebSocket,
    RtcPeerConnection,
    Navigator,
    WorkerNavigator,
    Permissions,
    PermissionStatus,
    NavigatorUAData,
    StorageManager,
    StorageEstimate,
    StorageBucketManager,
    StorageBucket,
    WorkerLocation,
    Screen,
    SpeechSynthesisUtterance,
    WebSocketError,
    WebSocketStream,
    DomRect,
    DomPoint,
    DomMatrix,
    ResizeObserver,
    PerformanceObserver,
    PerformanceObserverEntryList,
    PerformanceEntry,
    PerformanceNavigationTiming,
    PerformanceMark,
    PerformanceMeasure,
    PerformanceResourceTiming,
    EventCounts,
    PerformanceNavigation,
    PerformanceTiming,
    Animation,
    KeyframeEffect,
    MediaQueryList,
    MediaSource,
    MediaError,
    TextTrack,
    TextTrackList,
    TextTrackCue,
    TextTrackCueList,
    TrackEvent,
    VTTCue,
    Selection,
    History,
    Navigation,
    NavigationHistoryEntry,
    NavigationActivation,
    NavigationTransition,
    HtmlElement,
    Option,
    MutationObserver,
    MutationRecord,
    IntersectionObserver,
    IntersectionObserverEntry,
    Audio,
    Image,
    StyleSheet,
    StyleSheetList,
    MediaList,
    CssRuleList,
    CssRule,
    CssStyleRule,
    CssStyleSheet,
    CssKeywordValue,
    CssUnitValue,
    FontFace,
    FontFaceSet,
    FontFaceSetLoadEvent,
    AudioContext,
    AudioWorkletNode,
    OfflineAudioContext,
    EventTarget,
    XPathEvaluator,
    BaseAudioContext,
    AudioDestinationNode,
    OscillatorNode,
    DynamicsCompressorNode,
    AnalyserNode,
    AudioParam,
    AudioBuffer,
    Text,
    Comment,
    Touch,
    IdleDeadline,
    AbstractRange,
    Range,
    StaticRange,
    Url,
    UrlSearchParams,
    FormData,
    IndexedDb,
    IndexedDbVersionChangeEvent,
}

#[derive(Clone, Copy, PartialEq, Eq)]
pub(in crate::context_bootstrap) enum ConstructorPrototypeProperty {
    TemplateReadOnly,
    RuntimeInstalled { prototype_interface: &'static str },
}

#[derive(Clone, Copy)]
pub(in crate::context_bootstrap) struct ConstructorSpec {
    pub(in crate::context_bootstrap) name: &'static str,
    pub(in crate::context_bootstrap) parent: Option<&'static str>,
    pub(in crate::context_bootstrap) kind: ConstructorKind,
}

impl ConstructorSpec {
    pub(in crate::context_bootstrap) fn prototype_property(self) -> ConstructorPrototypeProperty {
        match self.kind {
            // HTML exposes these names as WebIDL LegacyFactoryFunction objects,
            // not as independent interface constructors. Their public
            // `prototype` property points at the backing element interface
            // prototype and must be installed after both objects exist.
            ConstructorKind::Audio => ConstructorPrototypeProperty::RuntimeInstalled {
                prototype_interface: "HTMLAudioElement",
            },
            ConstructorKind::Image => ConstructorPrototypeProperty::RuntimeInstalled {
                prototype_interface: "HTMLImageElement",
            },
            ConstructorKind::Option => ConstructorPrototypeProperty::RuntimeInstalled {
                prototype_interface: "HTMLOptionElement",
            },
            _ => ConstructorPrototypeProperty::TemplateReadOnly,
        }
    }
}
