import { useEffect, useMemo, useState } from "react";

import { deterministicWords, money, stableItems } from "../shared/data";
import { markReady } from "../shared/harness";
import { mountReact, type ReactCaseProps, useFrameUpdate } from "./support";

function ComplexProductsCase({ meta, spec }: ReactCaseProps) {
  const items = useMemo(() => stableItems(spec.seed, 36), [spec.seed]);
  const [selected, setSelected] = useState(0);
  const [mode, setMode] = useState("loading");
  useFrameUpdate(meta, () => {
    setSelected((spec.seed + spec.variant) % 7);
    setMode("ready");
  }, [spec.seed, spec.variant]);
  useEffect(() => {
    if (mode === "ready") markReady(meta, ["mounted", "react-complex-product-ready"]);
  }, [meta, mode]);

  const header = <header className="product-header"><a href="#home">Moli Suite</a><nav><a href="#work">Work</a><a href="#reports">Reports</a><a href="#team">Team</a></nav><button>Profile</button></header>;
  let body;
  if (spec.variant === 0) body = <><section className="hero"><h2>Operations overview</h2><p>{deterministicWords(spec.seed, 30)}</p></section><div className="metrics">{items.slice(0, 6).map((item) => <article key={item.id}><span>{item.status}</span><strong>{item.amount}</strong><small>{item.title}</small></article>)}</div><table><tbody>{items.slice(6, 22).map((item) => <tr key={item.id}><td>{item.title}</td><td>{item.owner}</td><td>{item.status}</td><td>{money(item.amount)}</td></tr>)}</tbody></table></>;
  else if (spec.variant === 1) body = <><aside><h2>Categories</h2>{["All", "Runtime", "DOM", "Network", "Storage"].map((name, index) => <button key={name} aria-pressed={selected === index}>{name}</button>)}</aside><section className="catalog">{items.slice(0, 20).map((item) => <article key={item.id}><div className="product-image" aria-label={item.title}>{item.title.slice(0, 2)}</div><h3>{item.title}</h3><p>{deterministicWords(item.amount, 12)}</p><strong>{money(item.amount)}</strong><button>Add</button></article>)}</section></>;
  else if (spec.variant === 2) body = <div className="kanban">{["new", "active", "paused", "done"].map((status) => <section key={status}><header><h2>{status}</h2><span>{items.filter((item) => item.status === status).length}</span></header>{items.filter((item) => item.status === status).map((item) => <article key={item.id}><h3>{item.title}</h3><p>{item.owner}</p><div>{item.tags.map((tag) => <span key={tag}>{tag}</span>)}</div></article>)}</section>)}</div>;
  else if (spec.variant === 3) body = <div className="mail"><aside><button>Compose</button>{["Inbox", "Starred", "Sent", "Drafts", "Archive"].map((name) => <a key={name} href={`#${name}`}>{name}</a>)}</aside><section className="messages">{items.slice(0, 16).map((item, index) => <article key={item.id} aria-current={selected === index}><strong>{item.owner}</strong><h3>{item.title}</h3><p>{deterministicWords(item.amount, 14)}</p><time>Jul {index + 1}</time></article>)}</section><article className="message-detail"><h2>{items[selected].title}</h2><p>From {items[selected].owner}</p><p>{deterministicWords(spec.seed, 90)}</p></article></div>;
  else if (spec.variant === 4) body = <div className="chat"><aside>{items.slice(0, 10).map((item, index) => <button key={item.id} aria-current={selected === index}><span>{item.owner.slice(0, 1)}</span>{item.owner}<small>{item.status}</small></button>)}</aside><section><header><h2>Compatibility team</h2><span>8 members</span></header><ol>{items.slice(8, 28).map((item, index) => <li key={item.id} data-own={index % 4 === 0}><strong>{item.owner}</strong><p>{item.title}: {deterministicWords(item.amount, 9)}</p><time>10:{String(index * 2).padStart(2, "0")}</time></li>)}</ol><form><input value="Draft message" readOnly /><button>Send</button></form></section></div>;
  else if (spec.variant === 5) body = <div className="docs"><aside><h2>Documentation</h2>{items.slice(0, 14).map((item) => <a key={item.id} href={`#${item.id}`}>{item.title}</a>)}</aside><article><p className="breadcrumbs">Docs / Runtime / Lifecycle</p><h2>Renderer lifecycle</h2>{Array.from({ length: 9 }, (_, index) => <section key={index}><h3 id={`section-${index}`}>{index + 1}. {items[index].title}</h3><p>{deterministicWords(spec.seed + index, 42)}</p>{index % 3 === 0 && <pre><code>{`const phase${index} = "ready";`}</code></pre>}</section>)}</article><nav aria-label="On this page">{items.slice(0, 9).map((item, index) => <a key={item.id} href={`#section-${index}`}>{item.title}</a>)}</nav></div>;
  else if (spec.variant === 6) body = <div className="booking"><section><h2>Find a workspace</h2><form><label>Location <input value="Shanghai" readOnly /></label><label>Date <input type="date" value="2026-08-12" readOnly /></label><label>People <input type="number" value="4" readOnly /></label><button>Search</button></form></section><section className="results">{items.slice(0, 14).map((item, index) => <article key={item.id}><div aria-label="Room preview">{index + 1}</div><h3>{item.title} Room</h3><p>{item.tags.join(" · ")}</p><strong>{money(item.amount)} / day</strong><button>Select</button></article>)}</section><aside><h2>Your booking</h2><p>{items[selected].title}</p><dl><dt>Subtotal</dt><dd>{money(items[selected].amount)}</dd><dt>Service</dt><dd>$12.00</dd></dl></aside></div>;
  else if (spec.variant === 7) body = <div className="issues"><aside><h2>Repositories</h2>{items.slice(0, 9).map((item) => <a key={item.id} href={`#${item.id}`}>{item.tags[0]}/{item.title}</a>)}</aside><section><header><h2>Issues</h2><button>New issue</button></header><div className="filters">{["Open", "Assigned", "Mentioned", "Closed"].map((name, index) => <button key={name} aria-pressed={selected === index}>{name}</button>)}</div>{items.slice(0, 24).map((item, index) => <article key={item.id}><span aria-label={item.status}>●</span><div><h3>#{1200 + index} {item.title}</h3><p>opened by {item.owner} · {item.tags.join(", ")}</p></div><strong>{index % 5}</strong></article>)}</section></div>;
  else if (spec.variant === 8) body = <div className="analytics"><section className="toolbar"><h2>Traffic analytics</h2><select value="30" onChange={() => {}}><option value="30">Last 30 days</option></select></section><div className="kpis">{items.slice(0, 5).map((item) => <article key={item.id}><span>{item.title}</span><strong>{item.amount * 13}</strong><small>+{item.amount % 27}%</small></article>)}</div><section className="chart" aria-label="Traffic bars">{items.slice(5, 25).map((item) => <div key={item.id} style={{ height: `${20 + item.amount % 80}px` }}><span>{item.amount}</span></div>)}</section><table><thead><tr><th>Page</th><th>Views</th><th>Users</th><th>Rate</th></tr></thead><tbody>{items.slice(10, 28).map((item) => <tr key={item.id}><td>/{item.tags[0]}/{item.id}</td><td>{item.amount}</td><td>{Math.floor(item.amount / 3)}</td><td>{item.amount % 100}%</td></tr>)}</tbody></table></div>;
  else body = <div className="invoice"><header><div><h2>INVOICE</h2><p>#MOLI-{spec.seed}</p></div><address>Moli Browser Labs<br />88 Runtime Road<br />Shanghai</address></header><section className="invoice-meta"><dl><dt>Issued</dt><dd>2026-07-30</dd><dt>Due</dt><dd>2026-08-30</dd><dt>Status</dt><dd>Draft</dd></dl><address>Bill to<br /><strong>Chromium Reference</strong><br />Automation Team</address></section><table><thead><tr><th>Description</th><th>Qty</th><th>Rate</th><th>Amount</th></tr></thead><tbody>{items.slice(0, 18).map((item, index) => <tr key={item.id}><td>{item.title}<small>{item.tags.join(", ")}</small></td><td>{index % 4 + 1}</td><td>{money(item.amount)}</td><td>{money(item.amount * (index % 4 + 1))}</td></tr>)}</tbody></table><footer><dl><dt>Subtotal</dt><dd>$18,420.00</dd><dt>Tax</dt><dd>$1,842.00</dd><dt>Total</dt><dd>$20,262.00</dd></dl><p>{deterministicWords(spec.seed, 32)}</p></footer></div>;
  return <main id="smoke-root" data-framework="react" data-family={meta.family} data-mode={mode}>{header}<h1>{meta.title}</h1><section data-case-body>{body}</section></main>;
}

export function mount(meta: ReactCaseProps["meta"], spec: ReactCaseProps["spec"]): void {
  mountReact(ComplexProductsCase, meta, spec);
}
