<script setup lang="ts">
import { nextTick, onMounted, ref } from "vue";

import { deterministicWords, money, stableItems } from "../shared/data";
import { captureFrame, markReady } from "../shared/harness";
import type { CaseSpec, SmokeMeta } from "../shared/types";

const props = defineProps<{ meta: SmokeMeta; spec: CaseSpec }>();
const items = stableItems(props.spec.seed, 36);
const selected = ref(0);
const mode = ref("loading");
const statuses = ["new", "active", "paused", "done"];
onMounted(async () => {
  await captureFrame(props.meta, "mounted");
  selected.value = (props.spec.seed + props.spec.variant) % 7;
  mode.value = "ready";
  await nextTick();
  markReady(props.meta, ["mounted", "vue-complex-product-ready"]);
});
</script>

<template>
  <main id="smoke-root" data-framework="vue" :data-family="meta.family" :data-mode="mode">
    <header class="product-header"><a href="#home">Moli Suite</a><nav><a href="#work">Work</a><a href="#reports">Reports</a><a href="#team">Team</a></nav><button>Profile</button></header>
    <h1>{{ meta.title }}</h1>
    <section data-case-body>
      <template v-if="spec.variant === 0"><section class="hero"><h2>Operations overview</h2><p>{{ deterministicWords(spec.seed, 30) }}</p></section><div class="metrics"><article v-for="item in items.slice(0, 6)" :key="item.id"><span>{{ item.status }}</span><strong>{{ item.amount }}</strong><small>{{ item.title }}</small></article></div><table><tbody><tr v-for="item in items.slice(6, 22)" :key="item.id"><td>{{ item.title }}</td><td>{{ item.owner }}</td><td>{{ item.status }}</td><td>{{ money(item.amount) }}</td></tr></tbody></table></template>
      <template v-else-if="spec.variant === 1"><aside><h2>Categories</h2><button v-for="(name, index) in ['All', 'Runtime', 'DOM', 'Network', 'Storage']" :key="name" :aria-pressed="selected === index">{{ name }}</button></aside><section class="catalog"><article v-for="item in items.slice(0, 20)" :key="item.id"><div class="product-image" :aria-label="item.title">{{ item.title.slice(0, 2) }}</div><h3>{{ item.title }}</h3><p>{{ deterministicWords(item.amount, 12) }}</p><strong>{{ money(item.amount) }}</strong><button>Add</button></article></section></template>
      <div v-else-if="spec.variant === 2" class="kanban"><section v-for="status in statuses" :key="status"><header><h2>{{ status }}</h2><span>{{ items.filter(item => item.status === status).length }}</span></header><article v-for="item in items.filter(item => item.status === status)" :key="item.id"><h3>{{ item.title }}</h3><p>{{ item.owner }}</p><div><span v-for="tag in item.tags" :key="tag">{{ tag }}</span></div></article></section></div>
      <div v-else-if="spec.variant === 3" class="mail"><aside><button>Compose</button><a v-for="name in ['Inbox', 'Starred', 'Sent', 'Drafts', 'Archive']" :key="name" :href="`#${name}`">{{ name }}</a></aside><section class="messages"><article v-for="(item, index) in items.slice(0, 16)" :key="item.id" :aria-current="selected === index"><strong>{{ item.owner }}</strong><h3>{{ item.title }}</h3><p>{{ deterministicWords(item.amount, 14) }}</p><time>Jul {{ index + 1 }}</time></article></section><article class="message-detail"><h2>{{ items[selected].title }}</h2><p>From {{ items[selected].owner }}</p><p>{{ deterministicWords(spec.seed, 90) }}</p></article></div>
      <div v-else-if="spec.variant === 4" class="chat"><aside><button v-for="(item, index) in items.slice(0, 10)" :key="item.id" :aria-current="selected === index"><span>{{ item.owner.slice(0, 1) }}</span>{{ item.owner }}<small>{{ item.status }}</small></button></aside><section><header><h2>Compatibility team</h2><span>8 members</span></header><ol><li v-for="(item, index) in items.slice(8, 28)" :key="item.id" :data-own="index % 4 === 0"><strong>{{ item.owner }}</strong><p>{{ item.title }}: {{ deterministicWords(item.amount, 9) }}</p><time>10:{{ String(index * 2).padStart(2, "0") }}</time></li></ol><form><input value="Draft message"><button>Send</button></form></section></div>
      <div v-else-if="spec.variant === 5" class="docs"><aside><h2>Documentation</h2><a v-for="item in items.slice(0, 14)" :key="item.id" :href="`#${item.id}`">{{ item.title }}</a></aside><article><p class="breadcrumbs">Docs / Runtime / Lifecycle</p><h2>Renderer lifecycle</h2><section v-for="index in 9" :key="index"><h3 :id="`section-${index - 1}`">{{ index }}. {{ items[index - 1].title }}</h3><p>{{ deterministicWords(spec.seed + index - 1, 42) }}</p><pre v-if="(index - 1) % 3 === 0"><code>const phase{{ index - 1 }} = "ready";</code></pre></section></article><nav aria-label="On this page"><a v-for="(item, index) in items.slice(0, 9)" :key="item.id" :href="`#section-${index}`">{{ item.title }}</a></nav></div>
      <div v-else-if="spec.variant === 6" class="booking"><section><h2>Find a workspace</h2><form><label>Location <input value="Shanghai"></label><label>Date <input type="date" value="2026-08-12"></label><label>People <input type="number" value="4"></label><button>Search</button></form></section><section class="results"><article v-for="(item, index) in items.slice(0, 14)" :key="item.id"><div :aria-label="`Room preview ${index + 1}`">{{ index + 1 }}</div><h3>{{ item.title }} Room</h3><p>{{ item.tags.join(" · ") }}</p><strong>{{ money(item.amount) }} / day</strong><button>Select</button></article></section><aside><h2>Your booking</h2><p>{{ items[selected].title }}</p><dl><dt>Subtotal</dt><dd>{{ money(items[selected].amount) }}</dd><dt>Service</dt><dd>$12.00</dd></dl></aside></div>
      <div v-else-if="spec.variant === 7" class="issues"><aside><h2>Repositories</h2><a v-for="item in items.slice(0, 9)" :key="item.id" :href="`#${item.id}`">{{ item.tags[0] }}/{{ item.title }}</a></aside><section><header><h2>Issues</h2><button>New issue</button></header><div class="filters"><button v-for="(name, index) in ['Open', 'Assigned', 'Mentioned', 'Closed']" :key="name" :aria-pressed="selected === index">{{ name }}</button></div><article v-for="(item, index) in items.slice(0, 24)" :key="item.id"><span :aria-label="item.status">●</span><div><h3>#{{ 1200 + index }} {{ item.title }}</h3><p>opened by {{ item.owner }} · {{ item.tags.join(", ") }}</p></div><strong>{{ index % 5 }}</strong></article></section></div>
      <div v-else-if="spec.variant === 8" class="analytics"><section class="toolbar"><h2>Traffic analytics</h2><select value="30"><option value="30">Last 30 days</option></select></section><div class="kpis"><article v-for="item in items.slice(0, 5)" :key="item.id"><span>{{ item.title }}</span><strong>{{ item.amount * 13 }}</strong><small>+{{ item.amount % 27 }}%</small></article></div><section class="chart" aria-label="Traffic bars"><div v-for="item in items.slice(5, 25)" :key="item.id" :style="{ height: `${20 + item.amount % 80}px` }"><span>{{ item.amount }}</span></div></section><table><thead><tr><th>Page</th><th>Views</th><th>Users</th><th>Rate</th></tr></thead><tbody><tr v-for="item in items.slice(10, 28)" :key="item.id"><td>/{{ item.tags[0] }}/{{ item.id }}</td><td>{{ item.amount }}</td><td>{{ Math.floor(item.amount / 3) }}</td><td>{{ item.amount % 100 }}%</td></tr></tbody></table></div>
      <div v-else class="invoice"><header><div><h2>INVOICE</h2><p>#MOLI-{{ spec.seed }}</p></div><address>Moli Browser Labs<br>88 Runtime Road<br>Shanghai</address></header><section class="invoice-meta"><dl><dt>Issued</dt><dd>2026-07-30</dd><dt>Due</dt><dd>2026-08-30</dd><dt>Status</dt><dd>Draft</dd></dl><address>Bill to<br><strong>Chromium Reference</strong><br>Automation Team</address></section><table><thead><tr><th>Description</th><th>Qty</th><th>Rate</th><th>Amount</th></tr></thead><tbody><tr v-for="(item, index) in items.slice(0, 18)" :key="item.id"><td>{{ item.title }}<small>{{ item.tags.join(", ") }}</small></td><td>{{ index % 4 + 1 }}</td><td>{{ money(item.amount) }}</td><td>{{ money(item.amount * (index % 4 + 1)) }}</td></tr></tbody></table><footer><dl><dt>Subtotal</dt><dd>$18,420.00</dd><dt>Tax</dt><dd>$1,842.00</dd><dt>Total</dt><dd>$20,262.00</dd></dl><p>{{ deterministicWords(spec.seed, 32) }}</p></footer></div>
    </section>
  </main>
</template>
