[package]
license.workspace = true
name = "moli-webidl"
version = "0.1.0"
edition = "2024"

[dependencies]
moli-v8-util = { path = "../moli-v8-util" }
moli-webidl-callback = { path = "../moli-webidl-callback" }
moli-webidl-derive = { path = "../moli-webidl-derive" }
v8 = "146.8.0"

[dev-dependencies]
moli-v8-test-util = { path = "../moli-v8-test-util" }

[lints]
workspace = true
