use super::*;

#[tokio::test]
async fn browser_context_document_cookie_facade_snapshot_keeps_capability_surface_without_live_page()
 {
    let conn = configured_connection_without_live_page().await;
    let snapshot = conn
        .browser_context
        .as_ref()
        .unwrap()
        .document_cookie_facade_snapshot();

    assert_eq!(
        snapshot.capability_surface.manager_surface.policy.overrides,
        BrowserCookieFacadeOverrides::default()
            .with_cookies_enabled(false)
            .with_storage_access_status(moli_cookie_jar::BrowserCookieStorageAccessStatus::Granted)
    );
    assert_eq!(
        snapshot
            .capability_surface
            .manager_surface
            .policy_gating
            .cookie_access_policy_verdict,
        super::cookie_manager_surface::BrowserContextCookieManagerAccessVerdict::NoLivePage
    );
    assert_eq!(
        snapshot
            .capability_surface
            .manager_surface
            .policy_gating
            .cookie_access_primary_block_reason,
        None
    );
    assert!(
        snapshot
            .capability_surface
            .manager_surface
            .policy_gating
            .cookie_access_blocked_reasons
            .is_empty()
    );
    assert_eq!(
        snapshot
            .capability_surface
            .manager_surface
            .policy_gating
            .cookie_write_policy_verdict,
        super::cookie_manager_surface::BrowserContextCookieManagerWriteVerdict::NoLivePage
    );
    assert_eq!(
        snapshot
            .capability_surface
            .manager_surface
            .policy_gating
            .cookie_write_primary_rejection_reason,
        None
    );
    assert!(
        snapshot
            .capability_surface
            .manager_surface
            .policy_gating
            .cookie_write_blocked_reasons
            .is_empty()
    );
    assert_eq!(
        snapshot
            .capability_surface
            .manager_surface
            .effective_gating
            .cookie_access_policy_verdict,
        super::cookie_manager_surface::BrowserContextCookieManagerAccessVerdict::NoLivePage
    );
    assert_eq!(
        snapshot
            .capability_surface
            .manager_surface
            .effective_gating
            .cookie_access_primary_block_reason,
        None
    );
    assert!(
        snapshot
            .capability_surface
            .manager_surface
            .effective_gating
            .cookie_access_blocked_reasons
            .is_empty()
    );
    assert_eq!(
        snapshot
            .capability_surface
            .manager_surface
            .effective_gating
            .cookie_write_policy_verdict,
        super::cookie_manager_surface::BrowserContextCookieManagerWriteVerdict::NoLivePage
    );
    assert_eq!(
        snapshot
            .capability_surface
            .manager_surface
            .effective_gating
            .cookie_write_primary_rejection_reason,
        None
    );
    assert!(
        snapshot
            .capability_surface
            .manager_surface
            .effective_gating
            .cookie_write_blocked_reasons
            .is_empty()
    );
    assert_eq!(
        snapshot
            .capability_surface
            .manager_surface
            .capability
            .cookie_access_verdict,
        super::cookie_manager_surface::BrowserContextCookieManagerAccessVerdict::NoLivePage
    );
    assert_eq!(
        snapshot
            .capability_surface
            .manager_surface
            .capability
            .cookie_write_verdict,
        super::cookie_manager_surface::BrowserContextCookieManagerWriteVerdict::NoLivePage
    );
    assert_eq!(
        snapshot
            .capability_surface
            .manager_surface
            .capability
            .cookie_access_enabled,
        None
    );
    assert_eq!(
        snapshot
            .capability_surface
            .manager_surface
            .capability
            .cookie_write_enabled,
        None
    );
    assert_eq!(
        snapshot
            .capability_surface
            .manager_surface
            .capability
            .cookie_access_primary_block_reason,
        None
    );
    assert_eq!(
        snapshot
            .capability_surface
            .manager_surface
            .capability
            .cookies_enabled_preference,
        None
    );
    assert_eq!(
        snapshot
            .capability_surface
            .manager_surface
            .capability
            .view_generation,
        None
    );
    assert!(
        snapshot
            .capability_surface
            .manager_surface
            .effective_context
            .is_none()
    );
    assert!(snapshot.capability_surface.capability.is_none());
    assert_eq!(
        snapshot.capability_surface.backend_connection_state,
        BrowserContextCookieBackendConnectionState::NoLivePage
    );
    assert_eq!(snapshot.capability_surface.first_cookie_request, None);
    assert!(snapshot.capability_surface.telemetry.is_none());
}
