[package]
license.workspace = true
name = "moli-curl"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
crossbeam-channel = "0.5.15"
curl = { version = "0.4.49", features = ["brotli", "http2", "poll_7_68_0", "static-curl", "static-ssl"] }
moli-dns-resolver = { path = "../moli-dns-resolver" }
parking_lot = "0.12"
tracing = "0.1.41"

[lints]
workspace = true
